export const PERSIST_REHYDRATE = 'persist/REHYDRATE'; // for redux-persist package
export const SET_LANG= 'SET_LANG';

export const CLIENT_LOGIN_SUCCESS= 'CLIENT_LOGIN_SUCCESS';
export const CLIENT_LOGOUT_SUCCESS= 'CLIENT_LOGOUT_SUCCESS';
export const CLIENT_PROFILE_UPDATE_SUCCESS= 'CLIENT_PROFILE_UPDATE_SUCCESS';
export const SET_CLIENT_LOGIN_IS_LOADING= 'SET_CLIENT_LOGIN_IS_LOADING';
export const SET_CLIENT_LOGOUT_IS_LOADING= 'SET_CLIENT_LOGOUT_IS_LOADING';
export const SET_CLIENT_PROFILE_UPDATE_IS_LOADING= 'SET_CLIENT_PROFILE_UPDATE_IS_LOADING';
export const SET_CLIENT_PASSWORD_UPDATE_IS_LOADING= 'SET_CLIENT_PASSWORD_UPDATE_IS_LOADING';
export const SET_CLIENT_PASSWORD_RESET_IS_LOADING= 'SET_CLIENT_PASSWORD_RESET_IS_LOADING';
export const SET_CLIENT_REGISTER_IS_LOADING= 'SET_CLIENT_REGISTER_IS_LOADING';
export const SET_CLIENT= 'SET_CLIENT';
export const SET_CLIENT_FETCH_IS_LOADING= 'SET_CLIENT_FETCH_IS_LOADING';

export const APPEND_CATEGORIES = 'APPEND_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_ARE_LOADING = 'SET_CATEGORIES_ARE_LOADING';

export const APPEND_PRODUCTS = 'APPEND_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_ARE_LOADING = 'SET_PRODUCTS_ARE_LOADING';

export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDERS_ARE_LOADING = 'SET_ORDERS_ARE_LOADING';

export const SET_CART_SHOP = 'SET_CART_SHOP';
export const SET_CHOICE_TYPE_FIXED = 'SET_CHOICE_TYPE_FIXED';
export const CREATE_CHOICE_TYPE_WITH_OPTIONS = 'CREATE_CHOICE_TYPE_WITH_OPTIONS';
export const UPDATE_COUNT_CHOICE_TYPE_WITH_OPTIONS = 'UPDATE_COUNT_CHOICE_TYPE_WITH_OPTIONS';
export const DELETE_CART_CHOICE_TYPE_WITH_OPTIONS = 'DELETE_CART_CHOICE_TYPE_WITH_OPTIONS';
export const SET_CART_CHOICES = 'SET_CART_CHOICES';
export const SET_CART_ADDRESS = 'SET_CART_ADDRESS';
export const SET_CART_PROMO_CODE = 'SET_CART_PROMO_CODE';
export const SET_CART_PROMO_CODE_IS_LOADING = 'SET_CART_PROMO_CODE_IS_LOADING';
export const SET_TYPE = 'SET_TYPE';
export const SET_ORDER_SUBMIT_IS_LOADING = 'SET_ORDER_SUBMIT_IS_LOADING';
export const SET_ADDITIONAL_NOTE = 'SET_ADDITIONAL_NOTE';
export const SET_SERVICE_AREA = 'SET_SERVICE_AREA';
export const SET_SERVICE_AREA_IS_LOADING = 'SET_SERVICE_AREA_IS_LOADING';
export const SET_ORDER_IN_PROGRESS = 'SET_ORDER_IN_PROGRESS';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const EMPTY_CART = 'EMPTY_CART';
export const CHANGE_SHOP = 'CHANGE_SHOP';

export const SHOW_CONFIRM_DIALOG = 'SHOW_CONFIRM_DIALOG';
export const HIDE_CONFIRM_DIALOG = 'HIDE_CONFIRM_DIALOG';

export const SHOW_PRODUCT_CREATE_DIALOG = 'SHOW_PRODUCT_CREATE_DIALOG';
export const HIDE_PRODUCT_CREATE_DIALOG = 'HIDE_PRODUCT_CREATE_DIALOG';
export const SHOW_PRODUCT_DELETE_DIALOG = 'SHOW_PRODUCT_DELETE_DIALOG';
export const HIDE_PRODUCT_DELETE_DIALOG = 'HIDE_PRODUCT_DELETE_DIALOG';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const OPEN_SIDE_DRAWER = 'OPEN_SIDE_DRAWER';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';

export const SET_LOYALTY_ACTIONS = 'SET_LOYALTY_ACTIONS';
export const SET_LOYALTY_ACTIONS_ARE_LOADING = 'SET_LOYALTY_ACTIONS_ARE_LOADING';
export const SET_PROMO_CODE_CREATE_LOADING = 'SET_PROMO_CODE_CREATE_LOADING';

export const SET_SHOP = 'SET_SHOP';
export const SET_SHOP_IS_LOADING = 'SET_SHOP_IS_LOADING';
export const SET_SHOPS = 'SET_SHOPS';
export const SET_SHOPS_ARE_LOADING = 'SET_SHOPS_ARE_LOADING';
